MAPLE-42 User 도메인 개발
web-dev-smash/maple-boss-server pull request #38
Opened 2022-05-07 10:48 UTC by chae0929c

2022-05-07 11:31 UTC, woogiekim requested changes

2022-05-07 11:31 UTC, woogiekim commented on common/src/main/java/com/maple/common/user/domain/User.java
> +        checkArgument(Strings.isNotBlank(email), "이메일은 필수입니다.");
에러메시지 이제 그냥 빼는거 어때요? 단순히 로그로 보는건데 에러메시지 없어도 솔직히 다 파악이 되서 조금 지치게 만드는 요소같아요

2022-05-07 11:31 UTC, woogiekim commented on common/src/test/java/com/maple/common/user/domain/UserTest.java
>  class UserTest {
블랭크 체크 테스트도 해줘야되요

2022-05-07 11:31 UTC, woogiekim commented on common/src/main/java/com/maple/common/user/domain/User.java
> +    @Column(length = 15 , nullable = false)
이렇게 제약조건 달았으면 플라이웨이 추가 하는거 필요해요

2022-05-07 15:09 UTC, chae0929c commented on common/src/main/java/com/maple/common/user/domain/User.java
> +        checkArgument(Strings.isNotBlank(email), "이메일은 필수입니다.");
넵 내일 할때 빼두겠습니다!

2022-05-08 02:21 UTC, woogiekim approved these changes

2022-05-08 05:24 UTC, merged