Maple 43 - USER Service 개발 이슈지만 도메인 개발 이슈
web-dev-smash/maple-boss-server pull request #48
Opened 2022-05-10 16:14 UTC by goyounha11

몇일 전 욱님과 준혁님과 얘기했을 때 서비스 보다는 도메인이 더  맞는 것 같아서 이슈 파서 하기로 했으나 까먹음 ㅎㅎ;;
서비스 개발할 때는 새로 서비스 파서 하겠습니댜

2022-05-10 23:12 UTC, woogiekim requested changes

2022-05-10 23:12 UTC, woogiekim commented on common/src/test/java/com/maple/common/user/domain/UserRepositoryTest.java
> +        assertThat(foundUser.getCreateAt()).isNotNull();
```suggestion
        assertThat(foundUser).isEqualTo(user);
```

2022-05-10 23:12 UTC, woogiekim commented on common/src/test/java/com/maple/common/user/service/DomainUserServiceTest.java
> +        assertThat(foundUser.getCreateAt()).isNotNull();
파라미터가 제대로 바인딩 되었는지만 확인해주세요

2022-05-11 02:22 UTC, peubel requested changes

2022-05-11 02:22 UTC, peubel commented on common/src/test/java/com/maple/common/user/domain/MockCertCodeGenerator.java
> +    @Override
필드 시작할때 엔터 한번 해주세요

2022-05-11 02:22 UTC, peubel commented on common/src/test/java/com/maple/common/user/domain/UserRepositoryTest.java
> +
generator 관련 검증이 필요할 거 같아요

2022-05-11 02:22 UTC, peubel commented on common/src/test/java/com/maple/common/user/domain/UserTest.java
generator 검증 여기두

2022-05-11 14:34 UTC, closed without merging